export const FETCH_ALL_MOVIE_REQUEST = 'FETCH_ALL_MOVIE_REQUEST';
export const FETCH_ALL_MOVIE_SUCCESS = 'FETCH_ALL_MOVIE_SUCCESS';
export const FETCH_ALL_MOVIE_FAILURE = 'FETCH_ALL_MOVIE_FAILURE';

export const FETCH_DETAIL_MOVIE_REQUEST = 'FETCH_DETAIL_MOVIE_REQUEST';
export const FETCH_DETAIL_MOVIE_SUCCESS = 'FETCH_DETAIL_MOVIE_SUCCESS';
export const FETCH_DETAIL_MOVIE_FAILURE = 'FETCH_DETAIL_MOVIE_FAILURE';